services:
  db:
    image: pgvector/pgvector:pg16 
    environment:
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: tracker_password
      POSTGRES_DB: news_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Добавляем проверку здоровья: контейнер будет пинговать сам себя
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker_user -d news_tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=news_tracker_db
      - DB_USER=tracker_user
      - DB_PASSWORD=tracker_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy # Ждем, пока healthcheck базы не скажет "OK"
      redis:
        condition: service_started

  celery:
    build: .
    command: celery -A core worker -l info  
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=news_tracker_db
      - DB_USER=tracker_user
      - DB_PASSWORD=tracker_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=news_tracker_db
      - DB_USER=tracker_user
      - DB_PASSWORD=tracker_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: