# Generated by Django 5.2.13 on 2026-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='explicit_feedback',
            field=models.IntegerField(default=0),
        ),
    ]
