# Generated by Django 5.2.13 on 2026-04-16 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='Анализ рациона подготавливается...')),
                ('suggestions', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
